CREATE TABLE [dbo].[Pizza]
(
  [Id] INT NOT NULL PRIMARY KEY
, [Name] NVARCHAR(50) NOT NULL
, [Price] MONEY NOT NULL
, [Description] NVARCHAR(1000) NOT NULL
, [Image] NVARCHAR(100) NOT NULL
, [IsDeleted] BIT NOT NULL
, [CreatedOn] DATETIME NOT NULL
, [ModifiedOn] DATETIME NOT NULL
, [DeletedOn] DATETIME NULL
);

